name = "DyNECT"
uuid = "aa322d10-53fc-4b1e-8c8f-7373483b5c2d"
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedVectorizations = "93c25245-795c-4f39-9b17-d28542eb77a0"
ParametricDAQP = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
BlockArrays = "1.6.3"
BlockDiagonals = "0.2.0"
LinearAlgebra = "1.11.0"
ParametricDAQP = "0.2.3"
Revise = "3.7.6"
