name = "DyNECT"
uuid = "858066fe-dd44-4a3d-96f2-b51f0b4e43b3"
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DAQP = "c47d62df-3981-49c8-9651-128b1cd08617"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Monviso = "1eb86b62-9073-48e6-9f04-fc5a45567986"
ParametricDAQP = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ParametricDAQP = "0.4.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
