name = "DyNECT"
uuid = "aa322d10-53fc-4b1e-8c8f-7373483b5c2d"
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
NamedVectorizations = "93c25245-795c-4f39-9b17-d28542eb77a0"
ParametricDAQP = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
BlockArrays = "1.6.3"
BlockDiagonals = "0.2.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
DynamicalSystems = "3.4.1"
GLMakie = "0.12.0"
LinearAlgebra = "1.11.0"
MAT = "0.10.7"
Makie = "0.23.0"
MatrixEquations = "2.5.1"
ParametricDAQP = "0.2.3"
Plots = "1.40.13"
Revise = "3.7.6"
